name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update Repositories
        run: sudo apt-get update
        
      - name: Reinstall autoconf  
        run: sudo apt-get remove autoconf && sudo apt-get install autoconf
        
      - name: Installing libtool
        run: sudo apt install autoconf libtool -y
        
      - name: Installing automake
        run: sudo apt-get install automake -y
      
      - name: Install autopoint
        run: sudo apt-get install autopoint -y
        
      - name: Install gettext
        run: sudo apt-get install gettext -y

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ../.
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
