name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update Repositories
        run: apt-get update
        
      - name: Removing autoconf
        run: apt-get purge --auto-remove autoconf
        
      - name: Installing dependencies
        run: apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        
      - name: Installing second set of dependencies
        run: apt-get install -y libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
        
      - name: Installing third set of dependencies
        run: apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
        
      - name: Installing Cython
        run: pip install cython
        
      - name: Installing cmake
        run: pip install cmake
        
      - name: Install autopoint
        run: apt-get install autopoint -y
      
      - name: Installing automake
        run: apt-get install automake -y
      
      - name: Reinstall autoconf  
        run: apt-get install autoconf -y
        
      - name: Installing libtool
        run: apt install autoconf libtool -y
        
      - name: Install gettext
        run: apt-get install gettext -y

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
