name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Installing dependencies
        run: apt update -qq > /dev/null && \
             apt install -qq --yes --no-install-recommends \
             autoconf \
             automake \
             autopoint \  
             build-essential \
             ccache \
             cmake \
             gettext \
             git \
             libffi-dev \
             libltdl-dev \
             libssl-dev \
             liblzma-dev \   
             libtool \
             openjdk-8-jdk \
             patch \
             pkg-config \
             python3-pip \
             python3-setuptools \
             sudo \
             unzip \
             zip \
             zlib1g-dev
        
      - name: Update Repositories
        run: sudo apt-get update
        
      - name: Reinstall autoconf  
        run: sudo apt-get remove autoconf && sudo apt-get install autoconf
      
      - name: Install autopoint
        run: sudo apt-get install autopoint -y
        
      - name: Install gettext
        run: sudo apt-get install gettext -y

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: . #<specify the directory of the app no don't mention this the app files are in root directory>
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
