name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
        # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
            python-version: 3.6 # optional
        
      - name: Update Repositories
        run: sudo apt-get update
      
      - name: Installing make
        run: sudo apt-get install -y make 
        
      - name: Checking autopoint  
        run: sudo ls /usr/bin/
        
      - name: Installing dependencies
        run: sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        
      - name: Installing second set of dependencies
        run: sudo apt-get install -y libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
        
      - name: Installing third set of dependencies
        run: sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
        
      - name: Installing Cython
        run: sudo pip install cython
        
      - name: Installing cmake
        run: sudo pip install cmake
      
      - name: Installing automake
        run: sudo apt-get install automake -y
        
      - name: Installing libtool
        run: sudo apt install autoconf libtool -y
        
      - name: Install gettext
        run: sudo apt-get install gettext -y
        
      - name: Printing path
        run: sudo echo $PATH
        
      - name: Checking autopoint
        run: sudo whereis autopoint
        
      - name: Checking autoconf
        run: sudo whereis autoconf
        
      - name: Printing error file
        run: sudo cat /usr/share/autoconf/Autom4te/FileUtils.pm

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: src
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
